name: "Update Some File and create PR to origin PR"

on:
  workflow_dispatch:

jobs:
  update-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm ./dist
      - run: echo "some change text\n" >> ./main.txt
      - uses: peter-evans/create-pull-request@v7
        if: ${{ always() }}
        with:
          commit-message: "chore: Update Fixture."
          branch: "bot/update-fixture"
          token: ${{ secrets.GITHUB_TOKEN }}
          
